
import { pt_BR as ptBRBundle, en as enBundle } from '@oracle-cx-commerce/resources';
import * as pt_BR from './locales/pt-BR'
import * as en from './locales/en'
import {buildResources} from '@oracle-cx-commerce/resources/utils';
import config from './config';

const widgetResourceKeys = [
  'actionCancel',
  'labelShippingOptions',
  'headingShippingOptions',
  'textEnterAShippingAddress',
  'textNoShippingMethods',
  'headingHomeDelivery',
  'headingShippingTo',
  "headingAddAddress",
  "headingEditAddress",
  'labelEditAddress',
  'labelOpenAddressBook',
  'textOpenAddressBookAndChooseAddress',
  'labelAddANewAddress',
  'actionMoveToWishList',
  'messagePartialBackOrder',
  'messageInsufficientStock',
  'messageInsufficientStockAtStore',
  'messageItemNoLongerAvailable',
  'messageQuantityManditory',
  'labelProductQuantity',
  'actionRemoveItem',
  'shippingSurchargeText',
  'textTotal',
  'textItemDetails',
  'textItemPrice',
  'textQuantity',
  'textGiftItem',
  'textSelectGiftMessage',
  'actionSelect',
  'textFreeProduct',
  'textFreeGift',
  'textFree',
  'textChange',
  'textSelectGift',
  'alertAddToCartAdding',
  'textInStock',
  'textOutOfStock',
  'textPreOrderable',
  'textBackOrderable',
  'textSelectOptionOnline',
  'actionAddToCartPreOrder',
  'alertTotalItemQuantityExceeded',
  'textGWPInvalidation',
  'alertOutOfStock',
  'alertCartHeading',
  'alertNoLongerForSale',
  'messageAtTheRate',
  'messagePriceChange',
  'alertPriceIncreased',
  'alertPriceDecreased',
  'messagePartialPreOrder',
  'messageStatusPreOrder',
  'messageStatusBackOrder',
  'closeLinkAltText',
  'textAllFieldsRequired',
  'textInvalidField',
  'textRequiredField',
  'labelNickName',
  'labelCompanyName',
  'labelFirstName',
  'labelLastName',
  'labelCountry',
  'labelZipCode',
  'labelState',
  'labelStreetAddress',
  'labelTownCity',
  'labelPhoneNumberOptional',
  'labelSaveAsANewProfileAddress',
  'labelSaveAsANewAccountAddress',
  'labelCancel',
  'buttonSaveAndContinue',
  'textAccountAddressBook',
  'textAccountAddress',
  'textProfileAddress',
  'textDefaultAddresses',
  'textProfileAddresses',
  'textInheritedAddresses',
  'textAddressesForThisAccount',
  'labelDefaultShippingAddress',
  'labelDefaultBillingAddress',
  'labelNoDefaultShippingAddressAvailable',
  'labelNoDefaultBillingAddressAvailable',
  'labelNoDefaultAddressesAvailable',
  'labelNoProfileAddressesAvailable',
  'labelNoAccountAddressesAvailable',
  'labelNoInheritedAddressesAvailable',
  'textLoading',
  'textLoadMoreAccountAddress',
  'textLoadMoreProfileAddress',
  'textLoadMoreInheritedAddress',
  'textUseThisAddress',
  'headingAddressBook',
  'labelAddressBook',
  'labelDefaultAddress',
  'headingAddShippingAddress',
  'headingEditShippingAddress',
  'alertShippingGroupUpdated',
  'alertAddressCreatedSuccessfully',
  'alertAddressChangedSuccessfully',
  'headingDeliveryAddress',
  'actionShowDetails',
  'actionHideDetails',
  'textPrice',
  'textSiteIcon',
  'shippingInfoLabel',
  'textSkuID',
  'LabelNeighboorhood',
  'LabelNumber',
  'LabelComplement',
  'freeShippingLabel'
];

const resources = buildResources({
  en: { ...enBundle, ...en },
  pt_BR: { ...ptBRBundle, ...pt_BR }
}, widgetResourceKeys)


export default TmbCheckoutSingleShippingDetails = {
  name: 'TmbCheckoutSingleShippingDetails',
  decription: 'Description of widget TmbCheckoutSingleShippingDetails',
  author: 'guilherme.vieira',
  fetchers: [],
  actions: [],
  availableToAllPages: false,
  resources,
  config,
  pageTypes: ['checkout-shipping'],
  requiresContext: ['checkout_shipping_context', 'cart_context']
};
