import { en as enBundle, pt_BR as pt_BR_Bundle } from '@oracle-cx-commerce/resources';
import * as en from './locales/en'
import * as pt_BR from './locales/pt-BR'
import { buildResources } from '@oracle-cx-commerce/resources/utils';

const widgetResourceKeys = [
  'actionAddNewCard',
  'actionDeleteCard',
  'actionMakeDefault',
  'alertMarkedDefaultCard',
  'headingSavedCreditCards',
  'labelDeleteCardLink',
  'labelMakeDefaultCardLink',
  'labelSavedCard',
  'textDefaultCard',
  'textExpiryDate',
  'textProfileCardHelper1',
  'textProfileCardHelper2',
  'actionCancel',
  'actionSave',
  'alertCardAdded',
  'buttonSaveAndContinue',
  'closeLinkAltText',
  'headingAddACreditCard',
  'headingAddBillingAddress',
  'headingBillingAddress',
  'headingEditBillingAddress',
  'labelAddANewAddress',
  'labelAddressBook',
  'labelCancel',
  'labelCardCVV',
  'labelCardNumber',
  'labelCompanyName',
  'labelCountry',
  'labelDefaultAddress',
  'labelDefaultBillingAddress',
  'labelDefaultPayment',
  'labelDefaultShippingAddress',
  'labelEditAddress',
  'labelExpiryDate',
  'labelExpiryMonth',
  'labelExpiryYear',
  'labelFirstName',
  'labelLastName',
  'labelNameOnCard',
  'labelNickName',
  'labelNoAccountAddressesAvailable',
  'labelNoDefaultAddressesAvailable',
  'labelNoInheritedAddressesAvailable',
  'labelNoProfileAddressesAvailable',
  'labelOpenAddressBook',
  'labelPhoneNumberOptional',
  'labelSaveAsANewAccountAddress',
  'labelSaveAsANewProfileAddress',
  'labelState',
  'labelStreetAddress',
  'labelTownCity',
  'labelZipCode',
  'textAccountAddressBook',
  'textAllFieldsRequired',
  'textAddressesForThisAccount',
  'textDefaultAddresses',
  'textEnterABillingAddress',
  'textInheritedAddresses',
  'textLoading',
  'textLoadMoreAccountAddress',
  'textLoadMoreInheritedAddress',
  'textLoadMoreProfileAddress',
  'textOpenAddressBookAndChooseBillingAddress',
  'textProfileAddresses',
  'textFieldInvalid',
  'textRequiredField',
  'textInvalidField',
  'textUseThisAddress',
  'widgetPresentationName'
];

const resources = buildResources({
  en: { ...enBundle, ...en },
  pt_BR: { ...pt_BR_Bundle, ...pt_BR }
}, widgetResourceKeys)

export default {
  name: 'TmbProfileSavedCards',
  decription: 'Description of widget TmbProfileSavedCards',
  author: 'ruan.matos',
  availableToAllPages: false,
  pageTypes: ['profile'],
  actions: ['listProfileSavedCards', 'notify', 'notifyClearAll', 'getOrganizationDefaultAddresses', 'saveCardToProfile'],
  fetchers: ['fetchCardTypes', 'fetchBillingCountries'],
  config: { properties: [], locales: {} },
  resources
};
